### ISSUE TITLE
every sidebar link is 404'ing

### ISSUE THREAD

**Issue by RudyOnRails** [samvera/samvera.github.io#321]
When I click on any pages on the sidebar, all I get is 404's.

http://samvera.github.io/search/introduction.html

**Comment by jmfrenzel** [comment]
The problem is the "search" in the link. 
Comparing the actual online version (Site last generated: May 25, 2018) http://samvera.github.io/index.html and a local checkout master https://github.com/samvera/samvera.github.io/commit/cd30ac0abd5b3565c4856a50f26bc085479bae6a I get the correct path without  'search'.

**Comment by jmfrenzel** [comment]
topnav search field seems broken too

**Comment by laritakr** [comment]
Closed, duplicate of #315
