### ISSUE TITLE
Document how to enable mediated deposit in hyrax

### ISSUE THREAD

**Issue by bess** [samvera/samvera.github.io#59]
WIP: https://github.com/projecthydra/projecthydra.github.io/blob/mediated_deposit/pages/hydra/developer_resources/workflow_and_mediated_deposit.md

**Comment by mark-dce** [comment]
In the [Via the UI](https://github.com/projecthydra/projecthydra.github.io/blob/mediated_deposit/pages/hydra/developer_resources/workflow_and_mediated_deposit.md#via-the-ui) setup step, the instructions say "Make sure you have an admin user".  There's alot loaded into that instruction, we should link out to instructions that describe how to do that.  This may be it's own ticket if those instructions don't exist.  Otherwise, this is a reminder to find and add the existing link.
