### ISSUE TITLE
Gather info for presentation to hydra virtual connect

### ISSUE THREAD

**Issue by jenlindner** [samvera/samvera.github.io#97]
https://wiki.duraspace.org/display/hydra/Call+for+IG+and+WG+updates

**Comment by elrayle** [comment]
Is this a lightening talk with slides or just a discussion?

If slides, we could show...
* Move from wiki to github.io
  * centralized easy to find documentaiton
  * more control over UI
  * content approval via PR process for adding/updating documentation
* Demo using screen capture
  * home page
  * 1-3 content pages as a quick teaser
* High Level Goals - provide developer documentation
  * increased code documentation
  * reference documentation
    * new to the community
    * existing/new developer reference
      * best practices
      * code patterns
      * how to
      * concepts
    * running in production info
    * community info
* Summary
  * creating new documentation
  * starting with links to existing wiki doc in some cases
  * transitioning existing docs from wiki(s)
  * a count of the number of pages with content

**Comment by elrayle** [comment]
That is probably way too much.  There is a 15 min slot for all the WG/IG and currently there are 10 groups signed up.  That means about 1 min per group.

**Comment by elrayle** [comment]
We have 2 minutes dedicated to each groups' update. We are hoping to have one slide deck with all the groups updates. Attached is the slide deck. Please add your updates in by July 7th.

Each group has 2 slides:

Slide 1: Group name and co-chairs

Slide 2: Please answer the following 3 questions:

1. What is the purpose of the group?
2. What have you achieved since last Connect? (Talk about activities group did)
3. What is the plan until next Connect? (Talk about upcoming activities/plans)

**Comment by bess** [comment]
Done: https://docs.google.com/presentation/d/1oC7kIS90F3TuHxgv3bsd75XfVASEOqzcELdtwYIkE0o/edit#slide=id.g2395b5df3f_0_41
